# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'reactnativefirebaseboilerplate' do
  pod 'React',
    :path => "../node_modules/react-native",
    :subspecs => [
      "Core",
      "ART",
      "RCTActionSheet",
      "RCTAnimation",
      "RCTCameraRoll",
      "RCTGeolocation",
      "RCTImage",
      "RCTNetwork",
      "RCTText",
      "RCTVibration",
      "RCTWebSocket",
      "DevSupport",
      "BatchedBridge"
    ]
  pod 'Yoga',
    :path => "../node_modules/react-native/ReactCommon/yoga"

  # Required by RNFirebase
  pod 'Firebase/AdMob'
  pod 'Firebase/Core'
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Crash'
  pod 'Firebase/Database'
  pod 'Firebase/DynamicLinks'
  pod 'Firebase/Messaging'
  pod 'Firebase/RemoteConfig'
  pod 'Firebase/Storage'
  pod 'RNFirebase', :path => '../node_modules/react-native-firebase'
end
